### PR TITLE
refactor: exposing WmsService from

### PR DESCRIPTION
**Pull request by MichaelLangbein**
@dlr-eoc/services-ogc

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/dlr-eoc/ukis-frontend-libraries/blob/master/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] The Project is [building and passes all tests](https://github.com/dlr-eoc/ukis-frontend-libraries/blob/master/DEVELOPMENT.md#further-you-can-test-and-build-locally) without errors

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: [66](https://github.com/dlr-eoc/ukis-frontend-libraries/issues/66)

`@dlr-eoc/serivces-ogc` does not expose the service `WmsService`.

## What is the new behavior?

With the service now exposed, we can more comfortably parse a WMS'es `GetCapabilities` document.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Is it part of one/more [packages](https://github.com/dlr-eoc/ukis-frontend-libraries/packages) and which?
 - `@dlr-eoc/services-ogc` only

### CODE REVIEW

**Comment by MichaelLangbein** [comment]
**Note**: I'd like to create a pre-release based on this PR, so that we can use the service in a currently ongoing sprint.
If there are no changes to be made from your point of view, I'd like to turn this into `v7.3.0-next.1`

**Comment by boeckMt** [comment]
> **Note**: I'd like to create a pre-release based on this PR, so that we can use the service in a currently ongoing sprint.
> If there are no changes to be made from your point of view, I'd like to turn this into `v7.3.0-next.1`

That's fine for me.

Do you like to export the other stuff as well or should it be private?


```ts
// public-api.ts 
...
export * from './lib/wps/wps_datatypes';
export * from './lib/wps/cache';
```

**Comment by MichaelLangbein** [comment]
Perfect, thanks a lot!

> Do you like to export the other stuff as well or should it be private?

Ah, that's very useful! I wasn't aware that Wps-Types are not being exported in services-ogc/wpsclient.
I'll update that in a bit - just need to do some research about how to export subsets of imported modules (in other words, how to `export WpsTypes from '@dlr-eoc/services-ogc'`).

Thanks!

**Comment by boeckMt** [comment]
> Perfect, thanks a lot!
> 
> > Do you like to export the other stuff as well or should it be private?
> 
> Ah, that's very useful! I wasn't aware that Wps-Types are not being exported in services-ogc/wpsclient.
> I'll update that in a bit - just need to do some research about how to export subsets of imported modules (in other words, how to `export WpsTypes from '@dlr-eoc/services-ogc'`).
> 
> Thanks!

Ah I think it is already exported from [@dlr-eoc/utils-ogc](https://github.com/dlr-eoc/ukis-frontend-libraries/blob/master/projects/utils-ogc/src/public-api.ts)

**Comment by MichaelLangbein** [comment]
> Ah I think it is already exported from [@dlr-eoc/utils-ogc](https://github.com/dlr-eoc/ukis-frontend-libraries/blob/master/projects/utils-ogc/src/public-api.ts) and `services-ogc/wpsclient` is using this.
> 
> So I think we can merge it?

Actually the types exported in `utils-ogc` were not exported in `services-ogc`. That means that the user would have to import both `utils-ogc` and `services-ogc` - which is unnecessarily complicated. I've updated that and committed the changes to this branch.

Unfortunately, I have created a pre-release named `7.3.0-next.1` before - so I had to create a new one, `7.3.0-next.2`, now. This should at least be the final artifact for this branch now.

**Pull request merged**
