### PR TITLE
Update Layers.ts

### PR DESCRIPTION
**Pull request by voinSR**
typo fix pupupFunktion --> popupFunction (could be a breaking change in come apps)

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/dlr-eoc/ukis-frontend-libraries/blob/master/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] The Project is [building and passes all tests](https://github.com/dlr-eoc/ukis-frontend-libraries/blob/master/DEVELOPMENT.md#further-you-can-test-and-build-locally) without errors

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

## Other information
Is it part of one/more [packages](https://github.com/dlr-eoc/ukis-frontend-libraries/packages) and which?

### CODE REVIEW

**Comment by boeckMt** [comment]
@voinSR Like you have mentioned, this typo is unfortunately a breaking change.

We also have to fix it everywhere where it is used. You can see it here https://github.com/dlr-eoc/ukis-frontend-libraries/pull/105/files and here https://github.com/dlr-eoc/ukis-frontend-libraries/search?q=pupupFunktion.

And can you also add it in the [CHANGELOG](https://github.com/dlr-eoc/ukis-frontend-libraries/blob/master/CHANGELOG.md).

**Comment by voinSR** [comment]
i just figured out that there were two typos in one atribute pupupFunktion should be actually popupFunction

**Comment by voinSR** [comment]
> 

ok i think i changed it everywhere

**Review by boeckMt — APPROVED** [review]
Looks good, thanks for that fix!

**Pull request merged**
